include:
  - local: '.ci/*.yml'
  - project: 'h3upperbounds/cicd-templates'
    file:
      - aws/assume_role.yaml

default:
  image: $NXRM_DOCKER_REGISTRY/alpine:latest
  tags:
    - h3internal-k8s-runner

stages:
  - stage
  - production
  - build
  - release-image
  - deploy

variables:
  MCP_SERVER_IMAGE: h3-mcp-server
