include:
  - project: 'h3upperbounds/cicd-templates'
    file:
      - aws/assume_role.yaml

stages:
  - stage
  - production

.merge:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always

.deploy-stage:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

.deploy-production:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d{4}-\d{2}-\d{2}\.\d+$/
      when: always


stage-merge:
  stage: stage
  image:
    name: $NXRM_DOCKER_REGISTRY_URL/aws-cli:latest
    pull_policy: always
  tags:
    - h3internal-k8s-runner
  script:
    - echo "Space holder for possible merge checks"
  rules:
    - !reference [.merge, rules]


# After merging into main, push a copy of the h3-cli to dev s3 bucket
stage-deploy:
  stage: stage
  image:
    name: $NXRM_DOCKER_REGISTRY_URL/aws-cli:latest
    pull_policy: always
  tags:
    - h3internal-k8s-runner
  variables:
    ASSUME_ROLE_ARN: '$GLAB_NON_PROD_ASSUME_ROLE_ARN'
    EXTERNAL_ID: '$GLAB_EXTERNAL_ID'
  script:
    # Get super secret access roles
    - !reference [.assume_role_scripts, assume_with_external_id]
    - aws sts get-caller-identity

    # strip out argo folder
    - rm -rf argocd
    - rm -rf .gitlab-ci.yml

    # wrap up code into .zip
    - zip -r h3-cli.zip ./*

    # Upload easy_install script to S3
    - sha256sum easy_install.sh > easy_install.sha256.checksum
    - aws s3 cp easy_install.sh s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp easy_install.sha256.checksum s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control

    # Upload h3-cli to S3
    - sha256sum h3-cli.zip > h3-cli.sha256.checksum
    - aws s3 cp h3-cli.zip s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp h3-cli.sha256.checksum s3://downloads-devstage-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
  rules:
    - !reference [.deploy-stage, rules]


# After merging into main and creating a tag, We want to push a copy of the h3-cli to prod s3 bucket
production-deploy:
  stage: production
  image:
    name: $NXRM_DOCKER_REGISTRY_URL/aws-cli:latest
    pull_policy: always
  tags:
    - us-c2-k8s-runner
  variables:
    ASSUME_ROLE_ARN: '$GLAB_PROD_US_ASSUME_ROLE_ARN'
    EXTERNAL_ID: '$GLAB_EXTERNAL_ID'
  script:
    - echo "Starting production-deploy for tag $CI_COMMIT_TAG"

    # Get super secret access roles
    - !reference [.assume_role_scripts, assume_with_external_id]
    - aws sts get-caller-identity

    # strip out argo folder
    - rm -rf argocd
    - rm -rf .gitlab-ci.yml

    # wrap up code into .zip
    - zip -r h3-cli.zip ./*

    # Upload to S3
    - sha256sum easy_install.sh > easy_install.sha256.checksum
    - aws s3 cp easy_install.sh s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp easy_install.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control

    # Upload to S3
    - sha256sum h3-cli.zip > h3-cli.sha256.checksum
    - aws s3 cp h3-cli.zip s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp h3-cli.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control

    # Upload to S3 with Tag name
    - EASY_INSTALL_NAME="easy_install-$CI_COMMIT_TAG"
    - sha256sum $EASY_INSTALL_NAME.sh > $EASY_INSTALL_NAME.sha256.checksum
    - aws s3 cp $EASY_INSTALL_NAME.sh s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp $EASY_INSTALL_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control

    # Upload to S3 with Tag name
    - H3_CLI_NAME="h3-cli-$CI_COMMIT_TAG"
    - mv h3-cli.zip $H3_CLI_NAME.zip
    - sha256sum H3_CLI_NAME.zip > H3_CLI_NAME.sha256.checksum
    - aws s3 cp H3_CLI_NAME.zip s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
    - aws s3 cp H3_CLI_NAME.sha256.checksum s3://downloads-prod-us-east-1/utilities/cli/ --metadata id=$CI_PIPELINE_ID --region us-east-1 --acl bucket-owner-full-control
  rules:
    - !reference [.deploy-production, rules]

# After merging to main, we want to update the public branch to then get mirrored to github.
push-to-public-branch:
  stage: production
  needs:
    - production-deploy
  image:
    # name: alpine/git:v2.49.0
    name: $NXRM_DOCKER_REGISTRY_URL/gerber:latest
    pull_policy: always
  tags:
    - h3internal-k8s-runner
  script:
    # Set up git settings
    - git config --global user.email "ci@example.com"
    - git config --global user.name "GitLab CI"

    # Fetch branches we are going to work with
    - git fetch origin main
    - git fetch origin public

    # Ensure we are on the main branch
    - git checkout main
    - git pull origin main

    # Create new branch to merge into public
    - TIMESTAMP=$(date +%Y%m%d%H%M%S)
    - BRANCH_NAME="public-$TIMESTAMP"
    - git checkout -b $BRANCH_NAME

    # Remove CI/CD files and folders
    - git rm -rf argocd
    - git rm -rf .gitlab-ci.yml
    - git commit -m "Release h3-cli $TIMESTAMP"

    # This is to ensure that the public branch only has the latest release without a commit history.
    - git checkout public
    - if [[ !$(git merge --squash $BRANCH_NAME) ]]; then
        echo "Squash merge failed";
        exit 1;
      fi
    - git commit -m "Release h3-cli $TIMESTAMP"

    # Push to public branch
    - git push origin public --force

  rules:
    - !reference [.deploy-production, rules]
